### ISSUE TITLE
Command Error

### ISSUE THREAD

**Issue by KleKlai** [OperatorFoundation/shapeshifter-dispatcher#11]
When running the command given in the readme file it do nothing
`go get -u github.com/OperatorFoundation/shapeshifter-dispatcher/shapeshifter-dispatcher`
[also when accessing the link](github.com/OperatorFoundation/shapeshifter-dispatcher/shapeshifter-dispatcher)
it return 404 page not found

**Comment by KleKlai** [comment]
OS: Windows 10
Go version: 1.11.4

Haven't try to run this on linux

**Comment by KwadroNaut** [comment]
Do you maybe already have it installed? It works fine here.

**Comment by Bluesaxorcist** [comment]
Turns out there was a typo in the link.  I fixed it in the readme so it should work now
