### ISSUE TITLE
Error building shapeshifter-dispatcher

### ISSUE THREAD

**Issue by br0metheus** [OperatorFoundation/shapeshifter-dispatcher#17]
In reference to issue #15 , I am also having this issue. Importing polish gives a 404 error. Looking through the directories locally, a listing shows:

/src/github.com/OperatorFoundation/shapeshifter-transports/transports/Replicant/polish#
total 16
-rw-rw-r-- 1 user user   84 Oct  2 23:30 config.go
-rw-rw-r-- 1 user user 1398 Oct  2 23:30 polish.go
-rw-rw-r-- 1 user user 6832 Oct  2 23:30 silver.go

I've tried building on Debian 10 and Ubuntu 18.04

**Comment by br0metheus** [comment]
The full error is:
go get -u github.com/OperatorFoundation/shapeshifter-dispatcher/shapeshifter-dispatcher
package github.com/OperatorFoundation/shapeshifter-transports/transports/replicant/polish: cannot find package "github.com/OperatorFoundation/shapeshifter-transports/transports/replicant/polish" in any of:
	/usr/local/go/src/github.com/OperatorFoundation/shapeshifter-transports/transports/replicant/polish (from $GOROOT)
	/home/user/go/src/github.com/OperatorFoundation/shapeshifter-transports/transports/replicant/polish (from $GOPATH)
package github.com/OperatorFoundation/shapeshifter-transports/transports/replicant/toneburst: cannot find package "github.com/OperatorFoundation/shapeshifter-transports/transports/replicant/toneburst" in any of:
	/usr/local/go/src/github.com/OperatorFoundation/shapeshifter-transports/transports/replicant/toneburst (from $GOROOT)
	/home/user/go/src/github.com/OperatorFoundation/shapeshifter-transports/transports/replicant/toneburst (from $GOPATH)

**Comment by KwadroNaut** [comment]
This will be fixed once someone merges https://github.com/OperatorFoundation/shapeshifter-transports/pull/6

**Comment by Bluesaxorcist** [comment]
This was fixed by a recent pull request by KwardoNaut!
