### ISSUE TITLE
Inconsistent iat documentation and handling

### ISSUE THREAD

**Issue by KwadroNaut** [OperatorFoundation/shapeshifter-dispatcher#18]
The README.MD refers to the timing   `iat-mode=0` and as well `iatMode` When using `iat-mode=0` at theclient you'll get: `(obfs4 transport missing iatMode argument)` The bridgeline that is produced by launching the server the first time will say `iat-mode=0`.

When looking at the [v.2 spec](https://github.com/Pluggable-Transports/Pluggable-Transports-spec/blob/master/releases/pt-2_0.pdf) you'll find 'iat-mode' in the appendix B, same for 2.1 draft. The GO Transports API and in the Dispatcher IPC Interface 2.1 draft you'll find both as well.

**Comment by Bluesaxorcist** [comment]
Thank you for the feedback!  i've corrected this inconsistency.  every instance of iatMode has been replaced with iat-mode
