### ISSUE TITLE
Consider tagging releases

### ISSUE THREAD

**Issue by KwadroNaut** [OperatorFoundation/shapeshifter-dispatcher#22]
The more activity, the higher the probability that something breaks. I'd like to be able to fetch the latest stable version and use that. When there are security updates or bug fixes, I'd like to be upgrade, without breaking changes like iat-mode vs iatmode, or if using a method that gets removed, it's great to know about that.

Thanks for considering!

**Comment by Bluesaxorcist** [comment]
the main reason we had to make a few of the changes like iat-mode was due mostly to conforming the spec.  We also plan to start implementing go modules soon, which from my understanding should help with different releases being unstable.  So far, the current release should hopefully be the most stable.  If not, i'm going to not close the issue yet so i can remember to provide a more stable version for you in the event that this one has major issues

**Comment by Bluesaxorcist** [comment]
We will start pushing regular releases moving forward!  Thanks again for the feedback

**Comment by KwadroNaut** [comment]
Thanks, makes sense!

> the main reason we had to make a few of the changes like iat-mode was due mostly to conforming the spec. 

Wait, which spec? I looked at https://github.com/Pluggable-Transports/Pluggable-Transports-spec/commit/8cab0d7bc8b3bf25596ad4cd4943e47a2d720a8b

- Go Tranport API v2.1 `Dial(nodeID *ntor.NodeID, publicKey *ntor.PublicKey, sessionKey *ntor.Keypair, iatMode int) *net.Conn`
- Dispatcher IPC Interface v2.1 `ARGS:cert=60RNHBMRrf+aOSPzSj8bD4ASGyyPl0mkaOUAQsAYljSkFB0G8B8m9fGvGJCpOxwoXS1baA;iatMode=0
`
- PTSpecV2Draft2.pdf `func New(nodeID *ntor.NodeID, publicKey *ntor.PublicKey, sessionKey *ntor.Keypair, iatMode int) *Transport` same document, just a bit lower: `ARGS:cert=HszPy3vWfjsESCEOo9ZBkRv6zQ/1mGHzc8arF0y2SpwFr3WhsMu8rK0zyaoyERfbz3ddFw,iat-mode=0`
Same issue in pt-2_0.pdf, I presume you understand my confusion.

**Comment by colthreepv** [comment]
Up for this issue.  
I wanted to create a docker image for this project, but version `3.0.0` does not compile, so I am forced to use `master`, thus creating an unreliable Docker Image 😞  relying on `latest` tag
