### ISSUE TITLE
-transparent -udp option not working? binding to TCP port instead

### ISSUE THREAD

**Issue by luckman212** [OperatorFoundation/shapeshifter-dispatcher#25]
**Question:** Is `-transparent -udp` working as of 1/2020? I've tried everything and no matter what, the server always binds to a tcp port instead of udp.

some version info:
macOS 10.15.2
go 1.13.5
shapeshifter-dispatcher 0.0.7

_this is in reference to https://github.com/OperatorFoundation/shapeshifter-dispatcher/issues/6#issuecomment-570077957 (which is a closed issue)_

**Comment by Bluesaxorcist** [comment]
We ran tests and have confirmed that we are not able to reproduce your issue.  We see shapeshifter-dispatcher binding to UDP when -udp is specified.  If you still are having issues, please post your full command line arguments so we can try to reproduce the issue
