### ISSUE TITLE
Should shapeshifter-dispatcher have a CI?

### ISSUE THREAD

**Issue by meskio** [OperatorFoundation/shapeshifter-dispatcher#33]
Now and then there are commits that leave shapeshifter-dispatcher in a status that doesn't compile. Maybe we can notice that faster if there was a CI that just compile the code.

A common CI used in github projects is travis, that will require to [activate the repo in travis](https://docs.travis-ci.com/user/tutorial/) and to add a `.travis.yml` in the [root of the repo with something like](https://docs.travis-ci.com/user/languages/go/):
```yaml
language: go
```

I'm happy to provide a pull-req with a .travis.yml, but someone with rights on the repo should activate it.

**Comment by blanu** [comment]
We have activated Travis CI for the repo as requested.

**Comment by meskio** [comment]
Amazing, thank you for enabling it. I just opened a pull-req to add the travis configuration (#34).
