### ISSUE TITLE
shapeshifter-dispatcher does not open any port on debian 11 server

### ISSUE THREAD

**Issue by morilp** [OperatorFoundation/shapeshifter-dispatcher#45]
i have a openvpn tcp 1194 with open port.
i did run below command on my server and nothig happend!
./go/bin/shapeshifter-dispatcher -transparent -server -state state -target 127.0.0.1:1194 -transport obfs4 -bindaddr obfs4-127.0.0.1:21194 -optionsFile ~/obfs4.json -logLevel DEBUG -enableLogging

my client command :
shapeshifter-dispatcher64.exe -transparent -client -state state -target my_server_ip:21194  -transports obfs4 -proxylistenaddr 127.0.0.1:999 -optionsFile obfs4.json -logLevel DEBUG -enableLogging

dispatcher.log:
[INFO] 2023/01/04 10:17 initializing transparent proxy
[INFO] 2023/01/04 10:17 initializing TCP transparent proxy
[INFO] 2023/01/04 10:17 dispatcher-0.0.7-dev - launched
[INFO] 2023/01/04 10:17 initializing server transport listeners
[INFO] 2023/01/04 10:17 shapeshifter-dispatcher - initializing transparentTCP server transport listeners

i did check the process and port with this command but:
netstat -lntp | grep 21194 -> show nothing
ps aux | grep shapshifter-dispatcher -> show nothing

my obfs4.json which is my config file:
{"cert": "PS9KSAXHMukTqFOrWcYHlil6z/gf6IZI4KtObc3TRKN3MltOIan5RZbkjCoqsA3lyB9XOQ", "iat-mode": "0"}

can you please tell me how can i open a openvpn connection with shapshifter?

**Comment by CryptoSax** [comment]
Obfs4 is no longer supported.  Shadow is the successor to Obfs4, so use that instead when the situation calls for it.  Here's an example server command for using Shadow:

./go/bin/shapeshifter-dispatcher -transparent -server -state state -target 127.0.0.1:1194 -transport shadow -bindaddr shadow-127.0.0.1:21194 -optionsFile ~/shadowServer.json -logLevel DEBUG -enableLogging

an example server config would be 

{
    "serverAddress": "127.0.0.1:2222",
    "serverPrivateKey": "afTZCabbt8CON/JNOlUSc9ezWDfZ4U2UgeeM8CruBSg=",
    "cipherName": "DARKSTAR",
    "transport": "Shadow"
}

to make a server and client config pair with a unique keypair, run the command 

./shapeshifter-dispatcher -transport shadow -serverIP 127.0.0.1:21194 --generateConfig

As of the PT 3.0 spec, we no longer use the -target flag on the client side, as it's specified in the config.

An example client command for shadow client would be

shapeshifter-dispatcher64.exe -transparent -client -state state -transports shadow -proxylistenaddr 127.0.0.1:999 -optionsFile shadowClient.json -logLevel DEBUG -enableLogging

an example shadow client config file would be

{
  "serverAddress": "127.0.0.1:1443",
  "serverPublicKey": "hLs2aXG4HgC3hB9qcFUkYHAYcBDCJXE5c61Bz808/h8=",
  "cipherName": "DARKSTAR",
  "transport": "Shadow",
}

These example config files should not be used as they contain the private key, so use the above command to generate a new pair
